// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DonationDBContext))]
    [Migration("20220924210444_ItemMasterMig")]
    partial class ItemMasterMig
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.ItemMaster", b =>
                {
                    b.Property<string>("itemCode")
                        .HasColumnType("nvarchar(25)");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("barcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("customerDescription")
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("imagePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("manageItemBy")
                        .HasColumnType("int");

                    b.Property<decimal>("maximumInventory")
                        .HasColumnType("decimal");

                    b.Property<decimal>("minimumInventory")
                        .HasColumnType("decimal");

                    b.Property<bool>("purchasedItem")
                        .HasColumnType("bit");

                    b.Property<string>("remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("salesItem")
                        .HasColumnType("bit");

                    b.Property<bool>("stockItem")
                        .HasColumnType("bit");

                    b.HasKey("itemCode");

                    b.ToTable("ItemMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
